"""Entity stamper.

Per chunk-shape D7 — entity normalization is required, not optional. Three
resolution rules per cross-doc-relationships §5:

  1. Direct slug match (JLBC URL gives slug for free)
  2. Alias map lookup (`samples/agency-slug-aliases.yaml`)
  3. Name-based match against entity catalog with rapidfuzz fallback

Loads the catalog + aliases YAMLs once at construction. `stamp(chunk, *,
source_url=None)` returns a new Chunk with `agency_canonical_id` set when
a match is found, plus the alias-hop chain on `chunk.alias_chain`.

If the chunk already has `agency_canonical_id`, stamp() is a passthrough —
re-running resolution can only weaken a deliberately-set value.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml
from rapidfuzz import fuzz, process

from chunking.agency_catalog import AgencyEntry, load_agency_catalog
from chunking.types import Chunk

_DEFAULT_CATALOG = Path(__file__).resolve().parent.parent / "samples" / "entity-catalog.yaml"
_DEFAULT_ALIASES = Path(__file__).resolve().parent.parent / "samples" / "agency-slug-aliases.yaml"
# Fund catalog is generated by scripts/build_fund_catalog.py — lives under data/
# alongside the other build outputs (discovery-cache, ingest-plan).
_DEFAULT_FUND_CATALOG = Path(__file__).resolve().parent.parent / "data" / "fund-catalog.yaml"

# Cross-cutting topic PDFs — never resolve to a per-agency canonical_id.
# Mirror of `_TOPIC_SLUGS` in ingest/discovery.py.
_TOPIC_SLUGS = frozenset({"capitaloutlay", "agencyindex", "crr", "tobacco", "csbg"})

# JLBC URL slug-extraction patterns. Two host families per url_conventions.py:
#   https://www.azjlbc.gov/<YY>baseline/<slug>.pdf       (FY23+ baselines)
#   https://www.azjlbc.gov/<YY>ar/<slug>.pdf             (FY23+ approps)
#   http://www.azleg.gov/jlbc/<YY>AR/<slug>.pdf          (FY15-FY22 approps)
_JLBC_URL_RE = re.compile(
    r"^https?://(?:www\.azjlbc\.gov/(?:\d{2}baseline|\d{2}ar)/"
    r"|www\.azleg\.gov/jlbc/\d{2}AR/)([a-z0-9_\-]+)\.pdf$",
    re.IGNORECASE,
)

# Fuzzy-match floor — rapidfuzz token_set_ratio. Plan: ≥ 85.
_FUZZY_THRESHOLD = 85


def slug_from_jlbc_url(url: str | None) -> str | None:
    """Extract the per-agency slug from a JLBC URL, or None if the URL is
    a non-JLBC publisher OR the slug is a cross-cutting topic file (which
    has no single canonical_id)."""
    if not url:
        return None
    m = _JLBC_URL_RE.match(url)
    if not m:
        return None
    slug = m.group(1).lower()
    if slug in _TOPIC_SLUGS:
        return None
    return slug


class EntityStamper:
    """Resolves a chunk's `agency_canonical_id` from URL, slug, or name."""

    def __init__(
        self,
        *,
        catalog_path: Path | str,
        aliases_path: Path | str,
        fund_catalog_path: Path | str | None = None,
    ) -> None:
        self._slug_to_id: dict[str, str] = {}
        self._name_to_id: dict[str, str] = {}
        self._all_names: list[str] = []  # for fuzzy match
        self._alias_to_canonical_slug: dict[str, str] = {}

        # Fund catalog state — populated only when fund_catalog_path is set.
        # Each fund's canonical_id keyed by every name form we want to match
        # (canonical_name, name_variants). Match order: longest-name-first
        # so 'Tobacco Tax Health Care Fund' wins over 'Tobacco Tax Fund'
        # when both substrings appear in the same chunk text.
        self._fund_name_to_id: dict[str, str] = {}
        self._fund_names_sorted: list[str] = []  # longest-first for substring scan

        self._load_catalog(Path(catalog_path))
        self._load_aliases(Path(aliases_path))
        if fund_catalog_path is not None:
            self._load_fund_catalog(Path(fund_catalog_path))

    @classmethod
    def from_default_paths(
        cls,
        *,
        fund_catalog_path: Path | str | None = "__default__",
    ) -> "EntityStamper":
        """Construct with the workspace's default catalog + aliases paths.

        `fund_catalog_path` defaults to data/fund-catalog.yaml when present,
        else None (fund stamping silently no-ops). Pass an explicit path to
        override; pass None to disable fund stamping; pass a non-existent
        path to surface a config error (FileNotFoundError).
        """
        if fund_catalog_path == "__default__":
            fund_catalog_path = (
                _DEFAULT_FUND_CATALOG if _DEFAULT_FUND_CATALOG.exists() else None
            )
        elif fund_catalog_path is not None:
            # Caller passed a real path — don't silently fall back if missing.
            p = Path(fund_catalog_path)
            if not p.exists():
                raise FileNotFoundError(
                    f"fund_catalog_path does not exist: {p}"
                )
        return cls(
            catalog_path=_DEFAULT_CATALOG,
            aliases_path=_DEFAULT_ALIASES,
            fund_catalog_path=fund_catalog_path,
        )

    # --- loading ------------------------------------------------------------

    def _load_catalog(self, path: Path) -> None:
        # Parsing lives in chunking.agency_catalog so non-stamping consumers
        # (UI filters, ingest metadata, title building) can get id→name without
        # building the alias map and fuzzy indexes this class needs.
        for entry in load_agency_catalog(path).values():
            if entry.slug:
                self._slug_to_id[entry.slug.lower()] = entry.canonical_id

            # Name → id index. Use casefolded form as key.
            for name in self._collect_names(entry):
                key = _normalize_for_match(name)
                if key and key not in self._name_to_id:
                    self._name_to_id[key] = entry.canonical_id
                if name and name not in self._all_names:
                    self._all_names.append(name)

    @staticmethod
    def _collect_names(entry: AgencyEntry) -> list[str]:
        names: list[str] = []
        if entry.canonical_name:
            names.append(entry.canonical_name)
            # Also add inverted form: 'X, Department of' <-> 'Department of X'
            inverted = _invert_comma_form(entry.canonical_name)
            if inverted and inverted != entry.canonical_name:
                names.append(inverted)
        # JLBC agency-index names plus any Gov-side alias, in that order —
        # the catalog loader already flattens both into name_variants.
        names.extend(entry.name_variants)
        return [n for n in names if n]

    def _load_aliases(self, path: Path) -> None:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for rename in raw.get("renames", []) or []:
            new_slug = rename.get("new_slug")
            if not new_slug:
                continue
            old_slug = rename.get("old_slug")
            if old_slug:
                self._alias_to_canonical_slug[old_slug.lower()] = new_slug.lower()
            for s in rename.get("old_slugs", []) or []:
                if s:
                    self._alias_to_canonical_slug[s.lower()] = new_slug.lower()

    def _load_fund_catalog(self, path: Path) -> None:
        """Load data/fund-catalog.yaml into the fund-name → canonical_id index.

        Indexes both `canonical_name` and any `name_variants`, casefolded.
        The sorted-by-length list at `_fund_names_sorted` drives the
        substring-scan in `_resolve_funds`.
        """
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for entry in raw.get("funds", []) or []:
            canonical_id = entry.get("canonical_id")
            if not canonical_id:
                continue
            for name in [entry.get("canonical_name"), *(entry.get("name_variants") or [])]:
                if not name:
                    continue
                key = name.casefold().strip()
                if key:
                    self._fund_name_to_id[key] = canonical_id
        # Substring scan walks longest-first so 'Tobacco Tax Health Care Fund'
        # matches before 'Tobacco Tax Fund' when both could overlap.
        self._fund_names_sorted = sorted(
            self._fund_name_to_id.keys(), key=len, reverse=True
        )

    # --- public API ---------------------------------------------------------

    def stamp(self, chunk: Chunk, *, source_url: str | None = None) -> Chunk:
        """Return a new Chunk with agency + fund canonical ids resolved.

        Agency: passthrough when chunk.agency_canonical_id is already set;
        otherwise apply the three-rule resolution (URL slug → alias hop →
        name match with fuzzy fallback) and stamp `alias_chain`.

        Fund: passthrough when chunk.fund_canonical_id is already set;
        otherwise scan section_path + text for fund names from the loaded
        catalog. Stamp `fund_canonical_id` with the first-detected fund
        and list any additional fund matches (in text order) on
        `fund_mentions`. Silently no-ops when no fund catalog was loaded.
        """
        updates: dict = {}

        if not chunk.agency_canonical_id:
            agency_id, alias_chain = self._resolve(
                section_path=chunk.section_path,
                text=chunk.text,
                source_url=source_url,
            )
            updates["agency_canonical_id"] = agency_id
            updates["alias_chain"] = alias_chain

        if not chunk.fund_canonical_id and self._fund_name_to_id:
            primary, mentions = self._resolve_funds(
                section_path=chunk.section_path,
                text=chunk.text,
            )
            updates["fund_canonical_id"] = primary
            updates["fund_mentions"] = mentions

        if not updates:
            return chunk
        return chunk.model_copy(update=updates)

    # --- resolution rules ---------------------------------------------------

    def _resolve(
        self,
        *,
        section_path: list[str],
        text: str,
        source_url: str | None,
    ) -> tuple[str | None, list[str]]:
        # Rule 1: slug from URL (with rule-2 alias hop folded in)
        slug = slug_from_jlbc_url(source_url)
        if slug:
            alias_chain: list[str] = []
            canonical_slug = self._alias_to_canonical_slug.get(slug, slug)
            if canonical_slug != slug:
                alias_chain.append(slug)
            canonical_id = self._slug_to_id.get(canonical_slug)
            if canonical_id:
                return canonical_id, alias_chain
            # Fall through: slug looked JLBC-shaped but isn't in the catalog.
            # Try names anyway.

        # Rule 3: name-based match across section_path + text
        candidates = list(section_path) + _split_text_into_candidate_phrases(text)

        # Exact (normalized) match first
        for cand in candidates:
            key = _normalize_for_match(cand)
            if key and key in self._name_to_id:
                return self._name_to_id[key], []

        # Inverted-form match: catalog has 'X, Department of'; chunk says
        # 'Department of X'. Generate inverted candidates and try those.
        for cand in candidates:
            inverted = _invert_comma_form(cand) or _invert_comma_form_reversed(cand)
            if not inverted:
                continue
            key = _normalize_for_match(inverted)
            if key and key in self._name_to_id:
                return self._name_to_id[key], []

        # Fuzzy fallback: rapidfuzz token_set_ratio against canonical_names.
        # The processor is load-bearing on TWO axes:
        #   1. Casefold — rapidfuzz's token_set_ratio is case-sensitive in 3.x
        #      without an explicit processor, so 'DEPARTMENT OF CORRECTIONS'
        #      vs 'Department of Corrections' scored ~19, far below the 85
        #      floor.
        #   2. NBSP normalization — Word writes bill headings with non-
        #      breaking spaces (\xa0) between tokens, which rapidfuzz does
        #      NOT tokenize on. Without normalization the heading token
        #      'Sec.\xa025.\xa0\xa0DEPARTMENT' fuses with the section number
        #      and never matches the catalog. Replacing \xa0 with regular
        #      space restores normal whitespace tokenization.
        for cand in candidates:
            best = process.extractOne(
                cand,
                self._all_names,
                scorer=fuzz.token_set_ratio,
                processor=_fuzzy_processor,
                score_cutoff=_FUZZY_THRESHOLD,
            )
            if best is not None:
                matched_name = best[0]
                key = _normalize_for_match(matched_name)
                canonical_id = self._name_to_id.get(key)
                if canonical_id:
                    return canonical_id, []

        return None, []

    # --- fund resolution ----------------------------------------------------

    def _resolve_funds(
        self,
        *,
        section_path: list[str],
        text: str,
    ) -> tuple[str | None, list[str]]:
        """Scan section_path + text in source order for fund-name mentions.

        Returns (primary_canonical_id, mentions_list). Primary = first
        fund detected. Mentions = every other unique fund detected
        afterwards, in first-seen order. The same fund mentioned multiple
        times appears once.

        Substring scan is longest-name-first so 'Tobacco Tax Health Care
        Fund' wins against 'Tobacco Tax Fund' on overlap. Once a span of
        text is consumed by one match, that span isn't reused — preserves
        the substring-uniqueness guarantee.
        """
        # Concatenate section_path then text into one search corpus, lowercase.
        # Source order: section_path first (most authoritative scope), then text.
        corpus_parts = [seg for seg in section_path if seg] + [text or ""]
        corpus = " | ".join(corpus_parts).casefold()
        if not corpus:
            return None, []

        # Find each fund name's earliest match position. Mark the matched
        # span so longer overlapping fund names take precedence.
        matches: list[tuple[int, str]] = []  # (start_index, canonical_id)
        consumed: list[tuple[int, int]] = []  # spans that have been claimed

        def _overlaps(start: int, end: int) -> bool:
            for cs, ce in consumed:
                if start < ce and end > cs:
                    return True
            return False

        for name in self._fund_names_sorted:
            # Find every occurrence of this fund name in the corpus.
            offset = 0
            while True:
                idx = corpus.find(name, offset)
                if idx == -1:
                    break
                end = idx + len(name)
                if not _overlaps(idx, end):
                    matches.append((idx, self._fund_name_to_id[name]))
                    consumed.append((idx, end))
                offset = end

        if not matches:
            return None, []

        # Sort by source-order position; dedupe canonical_ids in first-seen order.
        matches.sort(key=lambda pair: pair[0])
        seen: set[str] = set()
        ordered: list[str] = []
        for _, canonical_id in matches:
            if canonical_id in seen:
                continue
            seen.add(canonical_id)
            ordered.append(canonical_id)

        primary = ordered[0]
        mentions = ordered[1:]
        return primary, mentions


# --- text-normalization helpers ---------------------------------------------


_PUNCT_RE = re.compile(r"[^\w\s\-]")
_WS_RE = re.compile(r"\s+")


def _fuzzy_processor(s: str) -> str:
    """Pre-tokenization normalization for rapidfuzz token_set_ratio.

    Two transforms: NBSP→space (so Word's \\xa0 between tokens doesn't fuse
    them) and casefold (so ALL-CAPS bill headings match mixed-case catalog).
    """
    return s.replace("\xa0", " ").lower()


def _normalize_for_match(s: str) -> str:
    if not s:
        return ""
    out = s.casefold()
    out = _PUNCT_RE.sub(" ", out)
    out = _WS_RE.sub(" ", out).strip()
    return out


def _invert_comma_form(s: str) -> str | None:
    """Convert 'Corrections, Department of' → 'Department of Corrections'."""
    parts = [p.strip() for p in s.split(",", 1)]
    if len(parts) != 2:
        return None
    head, tail = parts
    if not tail:
        return None
    return f"{tail} {head}".strip()


def _invert_comma_form_reversed(s: str) -> str | None:
    """Convert 'Department of Corrections' → 'Corrections, Department of'.

    Looks for a leading 'Department of '/'Office of '/'Board of '/etc.; if
    found, swaps to comma form.
    """
    m = re.match(r"^(Department|Office|Board|Commission|Council|Authority)\s+of\s+(.+)$", s, re.IGNORECASE)
    if m:
        return f"{m.group(2).strip()}, {m.group(1).strip()} of"
    return None


def _split_text_into_candidate_phrases(text: str) -> list[str]:
    """Pull up to ~10 candidate name-phrases from chunk text. We don't run
    fuzzy match against every word in the body — just split into lines and
    use the first few non-trivial ones."""
    if not text:
        return []
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    return lines[:10]
