"""Entity stamper.

Per chunk-shape D7 — entity normalization is required, not optional. Three
resolution rules per cross-doc-relationships §5:

  1. Direct slug match (JLBC URL gives slug for free)
  2. Alias map lookup (`samples/agency-slug-aliases.yaml`)
  3. Name-based match against entity catalog with rapidfuzz fallback

Loads the catalog + aliases YAMLs once at construction. `stamp(chunk, *,
source_url=None)` returns a new Chunk with `agency_canonical_id` set when
a match is found, plus the alias-hop chain on `chunk.alias_chain`.

If the chunk already has `agency_canonical_id`, stamp() is a passthrough —
re-running resolution can only weaken a deliberately-set value.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml
from rapidfuzz import fuzz, process

from chunking.agency_catalog import AgencyEntry, load_agency_catalog
from chunking.types import Chunk

_DEFAULT_CATALOG = Path(__file__).resolve().parent.parent / "samples" / "entity-catalog.yaml"
_DEFAULT_ALIASES = Path(__file__).resolve().parent.parent / "samples" / "agency-slug-aliases.yaml"
# Fund catalog is generated by scripts/build_fund_catalog.py — lives under data/
# alongside the other build outputs (discovery-cache, ingest-plan).
_DEFAULT_FUND_CATALOG = Path(__file__).resolve().parent.parent / "data" / "fund-catalog.yaml"

# Cross-cutting topic PDFs — never resolve to a per-agency canonical_id.
# Mirror of `_TOPIC_SLUGS` in ingest/discovery.py.
_TOPIC_SLUGS = frozenset({"capitaloutlay", "agencyindex", "crr", "tobacco", "csbg"})

# JLBC URL slug-extraction patterns. Four azjlbc.gov directory conventions
# plus the legacy azleg.gov host:
#   https://www.azjlbc.gov/<YY>baseline/<slug>.pdf       (FY23+ baselines)
#   https://www.azjlbc.gov/<YY>ar/<slug>.pdf             (FY23+ approps)
#   https://www.azjlbc.gov/<YY>app/<slug>.pdf            (older approps)
#   https://www.azjlbc.gov/<YY>book<N>/<slug>.pdf        (older baselines)
#   http://www.azleg.gov/jlbc/<YY>AR/<slug>.pdf          (FY15-FY22 approps)
#
# WHY these four directories and not two (2026-08-16): JLBC published agency
# pages under `/NNapp/` (~1,294 live documents) and `/NNbookN/` (~141) as
# well as the `/NNbaseline/` and `/NNar/` this rule started with. Those
# ~1,448 documents therefore reached the fuzzy text rung with no slug at
# all -- and ~965 of them have a slug that IS a catalogued agency. That is
# the strongest witness in the ladder, discarded, on exactly the FY2005-2012
# era where the mis-labels concentrate. `store/book_family.py::_BOOK_DIR`
# already knew all four; the two modules disagreed and this is the one that
# assigned labels. Do not narrow this back to two directories.
_JLBC_URL_RE = re.compile(
    r"^https?://(?:www\.azjlbc\.gov/\d{2}(?:baseline|book\d*|ar|app)/"
    r"|www\.azleg\.gov/jlbc/\d{2}AR/)([a-z0-9_\-]+)\.pdf$",
    re.IGNORECASE,
)

# Fuzzy-match floor — rapidfuzz token_set_ratio. Plan: ≥ 85.
_FUZZY_THRESHOLD = 85

# Sub-programme slug prefix fallback (2026-08-16) — see the WHY block on
# _prefix_slug_match below for the measurement behind this rung.
_MIN_PREFIX_SLUG_LEN = 3

# The one measured false positive out of the 36 slugs the prefix rung
# recovers against the live corpus: 'appropveto' is JLBC's "Appropriation
# Vetoes" summary chapter (a legislative-process document), not a document
# about the agency slugged 'app' (the Legislature's budget-bill index). The
# two share their first 3 letters by coincidence only — measured, read by
# hand, and confirmed not an agency page. Add to this set only after the
# same hand-check; the whole point of the set is that these are exceptions,
# not a place to route around a bad measurement.
_PREFIX_MATCH_DENYLIST = frozenset({"appropveto"})


def slug_from_jlbc_url(url: str | None) -> str | None:
    """Extract the per-agency slug from a JLBC URL, or None if the URL is
    a non-JLBC publisher OR the slug is a cross-cutting topic file (which
    has no single canonical_id)."""
    if not url:
        return None
    m = _JLBC_URL_RE.match(url)
    if not m:
        return None
    slug = m.group(1).lower()
    if slug in _TOPIC_SLUGS:
        return None
    return slug


class EntityStamper:
    """Resolves a chunk's `agency_canonical_id` from URL, slug, or name."""

    def __init__(
        self,
        *,
        catalog_path: Path | str,
        aliases_path: Path | str,
        fund_catalog_path: Path | str | None = None,
    ) -> None:
        self._slug_to_id: dict[str, str] = {}
        # Catalogued slugs eligible to anchor a sub-programme prefix match
        # (>= _MIN_PREFIX_SLUG_LEN chars), longest-first so the longest
        # catalogued prefix wins — see _prefix_slug_match. Populated at the
        # end of _load_catalog, once every slug is known.
        self._prefix_slugs_longest_first: list[str] = []
        self._name_to_id: dict[str, str] = {}
        self._all_names: list[str] = []  # for fuzzy match
        self._alias_to_canonical_slug: dict[str, str] = {}

        # Agency-name substring index for the D2 multi-agency table scan.
        # Same shape (and same longest-first rationale) as the fund index
        # below: 'Public Safety, Department of' must win over a shorter
        # variant that is a substring of it.
        self._agency_scan_names: list[str] = []

        # Fund catalog state — populated only when fund_catalog_path is set.
        # Each fund's canonical_id keyed by every name form we want to match
        # (canonical_name, name_variants). Match order: longest-name-first
        # so 'Tobacco Tax Health Care Fund' wins over 'Tobacco Tax Fund'
        # when both substrings appear in the same chunk text.
        self._fund_name_to_id: dict[str, str] = {}
        self._fund_names_sorted: list[str] = []  # longest-first for substring scan

        self._load_catalog(Path(catalog_path))
        self._load_aliases(Path(aliases_path))
        if fund_catalog_path is not None:
            self._load_fund_catalog(Path(fund_catalog_path))

    @classmethod
    def from_default_paths(
        cls,
        *,
        fund_catalog_path: Path | str | None = "__default__",
    ) -> "EntityStamper":
        """Construct with the workspace's default catalog + aliases paths.

        `fund_catalog_path` defaults to data/fund-catalog.yaml when present,
        else None (fund stamping silently no-ops). Pass an explicit path to
        override; pass None to disable fund stamping; pass a non-existent
        path to surface a config error (FileNotFoundError).
        """
        if fund_catalog_path == "__default__":
            fund_catalog_path = (
                _DEFAULT_FUND_CATALOG if _DEFAULT_FUND_CATALOG.exists() else None
            )
        elif fund_catalog_path is not None:
            # Caller passed a real path — don't silently fall back if missing.
            p = Path(fund_catalog_path)
            if not p.exists():
                raise FileNotFoundError(
                    f"fund_catalog_path does not exist: {p}"
                )
        return cls(
            catalog_path=_DEFAULT_CATALOG,
            aliases_path=_DEFAULT_ALIASES,
            fund_catalog_path=fund_catalog_path,
        )

    # --- loading ------------------------------------------------------------

    def _load_catalog(self, path: Path) -> None:
        # Parsing lives in chunking.agency_catalog so non-stamping consumers
        # (UI filters, ingest metadata, title building) can get id→name without
        # building the alias map and fuzzy indexes this class needs.
        for entry in load_agency_catalog(path).values():
            if entry.slug:
                self._slug_to_id[entry.slug.lower()] = entry.canonical_id

            # Name → id index. Use casefolded form as key.
            for name in self._collect_names(entry):
                key = _normalize_for_match(name)
                if key and key not in self._name_to_id:
                    self._name_to_id[key] = entry.canonical_id
                if name and name not in self._all_names:
                    self._all_names.append(name)

        # WHY the length floor: the scan matches substrings, so a 3-4 char
        # agency variant ('DES') would fire inside unrelated words all over a
        # financial table. Every real acronym in the catalog ('AHCCCS') clears
        # 5 characters.
        self._agency_scan_names = sorted(
            (k for k in self._name_to_id if len(k) >= _MIN_SCAN_NAME_LEN),
            key=len,
            reverse=True,
        )

        self._prefix_slugs_longest_first = sorted(
            (s for s in self._slug_to_id if len(s) >= _MIN_PREFIX_SLUG_LEN),
            key=len,
            reverse=True,
        )

    @staticmethod
    def _collect_names(entry: AgencyEntry) -> list[str]:
        names: list[str] = []
        if entry.canonical_name:
            names.append(entry.canonical_name)
            # Also add inverted form: 'X, Department of' <-> 'Department of X'
            inverted = _invert_comma_form(entry.canonical_name)
            if inverted and inverted != entry.canonical_name:
                names.append(inverted)
        # JLBC agency-index names plus any Gov-side alias, in that order —
        # the catalog loader already flattens both into name_variants.
        names.extend(entry.name_variants)
        return [n for n in names if n]

    def _load_aliases(self, path: Path) -> None:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for rename in raw.get("renames", []) or []:
            new_slug = rename.get("new_slug")
            if not new_slug:
                continue
            old_slug = rename.get("old_slug")
            if old_slug:
                self._alias_to_canonical_slug[old_slug.lower()] = new_slug.lower()
            for s in rename.get("old_slugs", []) or []:
                if s:
                    self._alias_to_canonical_slug[s.lower()] = new_slug.lower()

    def _load_fund_catalog(self, path: Path) -> None:
        """Load data/fund-catalog.yaml into the fund-name → canonical_id index.

        Indexes both `canonical_name` and any `name_variants`, casefolded.
        The sorted-by-length list at `_fund_names_sorted` drives the
        substring-scan in `_resolve_funds`.
        """
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for entry in raw.get("funds", []) or []:
            canonical_id = entry.get("canonical_id")
            if not canonical_id:
                continue
            for name in [entry.get("canonical_name"), *(entry.get("name_variants") or [])]:
                if not name:
                    continue
                key = name.casefold().strip()
                if key:
                    self._fund_name_to_id[key] = canonical_id
        # Substring scan walks longest-first so 'Tobacco Tax Health Care Fund'
        # matches before 'Tobacco Tax Fund' when both could overlap.
        self._fund_names_sorted = sorted(
            self._fund_name_to_id.keys(), key=len, reverse=True
        )

    # --- public API ---------------------------------------------------------

    def stamp(self, chunk: Chunk, *, source_url: str | None = None) -> Chunk:
        """Return a new Chunk with agency + fund canonical ids resolved.

        Agency: passthrough when chunk.agency_canonical_id is already set;
        otherwise apply the three-rule resolution (URL slug → alias hop →
        name match with fuzzy fallback) and stamp `alias_chain`.

        Fund: passthrough when chunk.fund_canonical_id is already set;
        otherwise scan section_path + text for fund names from the loaded
        catalog. Stamp `fund_canonical_id` with the first-detected fund
        and list any additional fund matches (in text order) on
        `fund_mentions`. Silently no-ops when no fund catalog was loaded.
        """
        updates: dict = {}

        if not chunk.agency_canonical_id:
            agency_id, alias_chain = self._resolve(
                section_path=chunk.section_path,
                text=chunk.text,
                source_url=source_url,
            )
            updates["agency_canonical_id"] = agency_id
            updates["alias_chain"] = alias_chain

        if not chunk.fund_canonical_id and self._fund_name_to_id:
            primary, mentions = self._resolve_funds(
                section_path=chunk.section_path,
                text=chunk.text,
            )
            updates["fund_canonical_id"] = primary
            updates["fund_mentions"] = mentions

        if not updates:
            return chunk
        return chunk.model_copy(update=updates)

    def resolve_all(
        self, chunk: Chunk, *, source_url: str | None = None
    ) -> list[str]:
        """Every agency this chunk is about, primary first (decision D2).

        Narrative chunks resolve to at most one agency — a page that mentions
        a second agency in passing is not *about* it, and widening that would
        make every agency filter noisy.

        TABLE chunks are the case D2 exists for: a statewide schedule lists
        dozens of agencies in one chunk, and scalar resolution keeps whichever
        matched first, so filtering by any of the others silently misses the
        row. For tables we scan the whole text for catalog names and return
        all of them, with the scalar answer pinned to the front so
        single-agency labels downstream keep showing the same thing.

        Returned at the ROW layer (`ingest.lance_writer.chunk_to_lance_row`
        takes this list) rather than on the Chunk model, matching how the old
        Postgres loader promoted scalar → array.
        """
        primary = chunk.agency_canonical_id
        if not primary:
            primary, _chain = self._resolve(
                section_path=chunk.section_path,
                text=chunk.text,
                source_url=source_url,
            )

        if not chunk.is_table:
            return [primary] if primary else []

        found = _scan_for_names(
            corpus=_normalize_for_match(
                " | ".join([seg for seg in chunk.section_path if seg] + [chunk.text or ""])
            ),
            names_longest_first=self._agency_scan_names,
            name_to_id=self._name_to_id,
        )
        if primary:
            # Pin the scalar answer first without duplicating it.
            found = [primary] + [i for i in found if i != primary]
        return found

    # --- resolution rules ---------------------------------------------------

    def _resolve(
        self,
        *,
        section_path: list[str],
        text: str,
        source_url: str | None,
    ) -> tuple[str | None, list[str]]:
        # Rule 1: slug from URL (with rule-2 alias hop folded in)
        slug = slug_from_jlbc_url(source_url)
        if slug:
            alias_chain: list[str] = []
            canonical_slug = self._alias_to_canonical_slug.get(slug, slug)
            if canonical_slug != slug:
                alias_chain.append(slug)
            canonical_id = self._slug_to_id.get(canonical_slug)
            if canonical_id:
                return canonical_id, alias_chain

            # Rung 1b: sub-programme slug prefix fallback. See the WHY block
            # on _prefix_slug_match — measured to recover 36/195 real
            # documents from older (~FY2005-2012) editions where JLBC split
            # a large agency into several sub-programme PDFs whose slugs
            # ('axsacute', 'dhsbehav', ...) were never added to the catalog.
            prefix_id = self._prefix_slug_match(canonical_slug)
            if prefix_id:
                return prefix_id, alias_chain

            # Fall through: slug looked JLBC-shaped but isn't in the catalog.
            # Try names anyway.

        # Rule 3: name-based match across section_path + text
        candidates = list(section_path) + _split_text_into_candidate_phrases(text)

        # Exact (normalized) match first
        for cand in candidates:
            key = _normalize_for_match(cand)
            if key and key in self._name_to_id:
                return self._name_to_id[key], []

        # Inverted-form match: catalog has 'X, Department of'; chunk says
        # 'Department of X'. Generate inverted candidates and try those.
        for cand in candidates:
            inverted = _invert_comma_form(cand) or _invert_comma_form_reversed(cand)
            if not inverted:
                continue
            key = _normalize_for_match(inverted)
            if key and key in self._name_to_id:
                return self._name_to_id[key], []

        # Fuzzy fallback: rapidfuzz token_sort_ratio against canonical_names.
        #
        # WHY token_sort_ratio and not token_set_ratio (2026-08-16 — this is
        # the defect that mis-labelled 732 of the 992 documents stamped
        # 'agency:ost', making one small regulatory board the largest agency
        # in the corpus, above Corrections and AHCCCS): token_set_ratio
        # compares token SETS, so a candidate whose tokens are a SUBSET of a
        # catalog name scores 100 no matter how little of the name it
        # covers. Measured against the real Osteopathic catalog entry:
        #
        #     candidate                    token_set_ratio  token_sort_ratio
        #     'Arizona'                              100                14
        #     'Medicine'                             100                16
        #     'Board of'                              77                16
        #     'Board of Barbers' vs                   97                97
        #       'Barbers, Board of'
        #     'DEPARTMENT OF CORRECTIONS' vs          88                88
        #       'Corrections, State Department of'
        #
        # The candidates are the first ten non-blank lines of a chunk plus
        # its section_path, so a page whose header merely says "Arizona"
        # reached a 100-way tie under token_set_ratio — and extractOne broke
        # that tie by CATALOG ORDER, not by evidence.
        #
        # token_sort_ratio separates the two classes completely at the
        # existing floor of 85. It sorts tokens before comparing, so it
        # still handles the reordered-name case the scorer was originally
        # chosen for ('Board of Barbers' vs 'Barbers, Board of' both stay at
        # 97), while penalising the length mismatch token_set_ratio ignores.
        # Switching costs NOTHING on candidates carrying extra words —
        # 'Board of Barbers   Executive Director: Mario J. Herrera' scores
        # 64 under token_set_ratio and 46 under token_sort_ratio, both
        # already below the 85 floor. The fuzzy rung only ever fires on
        # short, clean candidate lines, which is exactly where the defect
        # lived.
        #
        # The processor is load-bearing on TWO axes, unrelated to the scorer
        # choice above:
        #   1. Casefold — rapidfuzz's ratio scorers are case-sensitive in 3.x
        #      without an explicit processor, so 'DEPARTMENT OF CORRECTIONS'
        #      vs 'Department of Corrections' scored ~19, far below the 85
        #      floor.
        #   2. NBSP normalization — Word writes bill headings with non-
        #      breaking spaces (\xa0) between tokens, which rapidfuzz does
        #      NOT tokenize on. Without normalization the heading token
        #      'Sec.\xa025.\xa0\xa0DEPARTMENT' fuses with the section number
        #      and never matches the catalog. Replacing \xa0 with regular
        #      space restores normal whitespace tokenization.
        #
        # Ties are refused, not broken by catalog order. `process.extract`
        # (plural) is used instead of `extractOne` so every name at the top
        # score is visible; if two or more of them map to DIFFERENT
        # canonical ids, that candidate line is not evidence for any one of
        # them and is skipped. This is deliberately per-CANDIDATE, not
        # whole-chunk: a later, cleaner line can still resolve even if an
        # earlier one was ambiguous. An unlabelled chunk costs only a
        # ranking preference (agency is a PREFERENCE, not a filter — see
        # CLAUDE.md), while a wrong guess costs a wrong agency facet, which
        # is what 732 mis-labelled documents look like.
        for cand in candidates:
            matches = process.extract(
                cand,
                self._all_names,
                scorer=fuzz.token_sort_ratio,
                processor=_fuzzy_processor,
                score_cutoff=_FUZZY_THRESHOLD,
                limit=5,
            )
            if not matches:
                continue
            top_score = matches[0][1]
            top_ids = {
                self._name_to_id[key]
                for name, score, _idx in matches
                if score == top_score
                for key in [_normalize_for_match(name)]
                if key in self._name_to_id
            }
            if len(top_ids) == 1:
                return next(iter(top_ids)), []
            # len(top_ids) == 0: matched name(s) not in the index (shouldn't
            # happen, _all_names is built from indexed names) — treat as no
            # match. len(top_ids) > 1: a genuine tie between distinct
            # agencies — refuse rather than guess, per the WHY above.

        return None, []

    def _prefix_slug_match(self, slug: str) -> str | None:
        """Sub-programme slug fallback for rung 1 (2026-08-16).

        WHAT this recovers: in older JLBC editions (roughly FY2005-2012),
        several large agencies were published as multiple sub-programme
        documents instead of one per-agency file — e.g. AHCCCS Acute Care
        as 'axsacute.pdf', AHCCCS Administration as 'axsadmn.pdf', neither
        of which is the catalogued 'axs' slug. The agency catalog only
        knows the whole-agency slug, so the direct lookup above always
        misses these, and (correctly, since the fuzzy text rung was just
        tightened to stop guessing from a single shared word) the text
        rung refuses them too — before this fallback they lost their
        AHCCCS label entirely.

        MEASURED (controller, live corpus, 2026-08-16): "does the
        catalogued slug is-a-prefix-of the uncatalogued URL slug" recovers
        36 slugs / 195 documents, 35 of them unambiguously correct — see
        _SUB_PROGRAMME_SLUG_TO_AGENCY in tests/test_entity_stamper.py for
        the full pinned list (ade/axs/des/dhs/doa/dot sub-programmes plus
        judsuperior -> judsup). Everything else uncatalogued is JLBC's
        numbered summary chapters ('302', '341-353', ...) — no catalogued
        slug is ever a prefix of those, so they correctly stay unresolved.

        The one measured false positive, 'appropveto' -> 'app', is refused
        via _PREFIX_MATCH_DENYLIST rather than by tightening the length
        floor (which would have thrown away real recoveries like the
        3-char 'axs' and 'des' groups).

        Longest catalogued prefix wins (`_prefix_slugs_longest_first` is
        pre-sorted): 'judsuperior' must resolve via the 6-char 'judsup',
        not stop at some shorter accidental match. A floor of
        `_MIN_PREFIX_SLUG_LEN = 3` keeps 2-character catalogued slugs (the
        real catalog has 'cf', 'cs') from ever anchoring a match — at that
        length they would fire inside unrelated slugs across the corpus,
        the same over-eager-substring failure mode the fuzzy rung was just
        fixed for.
        """
        if slug in _PREFIX_MATCH_DENYLIST:
            return None
        for catalog_slug in self._prefix_slugs_longest_first:
            if slug.startswith(catalog_slug):
                return self._slug_to_id.get(catalog_slug)
        return None

    # --- fund resolution ----------------------------------------------------

    def _resolve_funds(
        self,
        *,
        section_path: list[str],
        text: str,
    ) -> tuple[str | None, list[str]]:
        """Scan section_path + text in source order for fund-name mentions.

        Returns (primary_canonical_id, mentions_list). Primary = first
        fund detected. Mentions = every other unique fund detected
        afterwards, in first-seen order. The same fund mentioned multiple
        times appears once.

        Substring scan is longest-name-first so 'Tobacco Tax Health Care
        Fund' wins against 'Tobacco Tax Fund' on overlap. Once a span of
        text is consumed by one match, that span isn't reused — preserves
        the substring-uniqueness guarantee.
        """
        # Concatenate section_path then text into one search corpus, lowercase.
        # Source order: section_path first (most authoritative scope), then text.
        corpus_parts = [seg for seg in section_path if seg] + [text or ""]
        corpus = " | ".join(corpus_parts).casefold()
        if not corpus:
            return None, []

        ordered = _scan_for_names(
            corpus=corpus,
            names_longest_first=self._fund_names_sorted,
            name_to_id=self._fund_name_to_id,
        )
        if not ordered:
            return None, []
        return ordered[0], ordered[1:]


# --- name scanning -----------------------------------------------------------

# Shortest catalog name the substring scan will trust. See the WHY at the
# call site in _load_catalog.
_MIN_SCAN_NAME_LEN = 5


def _scan_for_names(
    *,
    corpus: str,
    names_longest_first: list[str],
    name_to_id: dict[str, str],
) -> list[str]:
    """Canonical ids named in `corpus`, in first-mention order, deduped.

    `corpus` and the names must already be normalized the same way (both
    casefolded for funds; both run through _normalize_for_match for
    agencies) — this does a plain substring find, so a mismatch in
    normalization means silent zero matches.

    Longest-name-first with span claiming is what makes overlapping names
    behave: 'Tobacco Tax Health Care Fund' consumes its span before
    'Tobacco Tax Fund' can match inside it.
    """
    if not corpus:
        return []

    matches: list[tuple[int, str]] = []  # (start_index, canonical_id)
    consumed: list[tuple[int, int]] = []  # spans already claimed

    def _overlaps(start: int, end: int) -> bool:
        return any(start < ce and end > cs for cs, ce in consumed)

    for name in names_longest_first:
        offset = 0
        while True:
            idx = corpus.find(name, offset)
            if idx == -1:
                break
            end = idx + len(name)
            if not _overlaps(idx, end):
                matches.append((idx, name_to_id[name]))
                consumed.append((idx, end))
            offset = end

    matches.sort(key=lambda pair: pair[0])
    seen: set[str] = set()
    ordered: list[str] = []
    for _, canonical_id in matches:
        if canonical_id not in seen:
            seen.add(canonical_id)
            ordered.append(canonical_id)
    return ordered


# --- text-normalization helpers ---------------------------------------------


_PUNCT_RE = re.compile(r"[^\w\s\-]")
_WS_RE = re.compile(r"\s+")


def _fuzzy_processor(s: str) -> str:
    """Pre-tokenization normalization for rapidfuzz token_set_ratio.

    Two transforms: NBSP→space (so Word's \\xa0 between tokens doesn't fuse
    them) and casefold (so ALL-CAPS bill headings match mixed-case catalog).
    """
    return s.replace("\xa0", " ").lower()


def _normalize_for_match(s: str) -> str:
    if not s:
        return ""
    out = s.casefold()
    out = _PUNCT_RE.sub(" ", out)
    out = _WS_RE.sub(" ", out).strip()
    return out


def _invert_comma_form(s: str) -> str | None:
    """Convert 'Corrections, Department of' → 'Department of Corrections'."""
    parts = [p.strip() for p in s.split(",", 1)]
    if len(parts) != 2:
        return None
    head, tail = parts
    if not tail:
        return None
    return f"{tail} {head}".strip()


def _invert_comma_form_reversed(s: str) -> str | None:
    """Convert 'Department of Corrections' → 'Corrections, Department of'.

    Looks for a leading 'Department of '/'Office of '/'Board of '/etc.; if
    found, swaps to comma form.
    """
    m = re.match(r"^(Department|Office|Board|Commission|Council|Authority)\s+of\s+(.+)$", s, re.IGNORECASE)
    if m:
        return f"{m.group(2).strip()}, {m.group(1).strip()} of"
    return None


def _split_text_into_candidate_phrases(text: str) -> list[str]:
    """Pull up to ~10 candidate name-phrases from chunk text. We don't run
    fuzzy match against every word in the body — just split into lines and
    use the first few non-trivial ones."""
    if not text:
        return []
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    return lines[:10]
