"""Generate db/migrations/0003_seed_catalogs.sql from the YAML catalogs.

Runs once whenever samples/entity-catalog.yaml or data/fund-catalog.yaml changes.
Output is checked in. Phase 1b WS1, Task 1.2 Step 3.

Usage:
    uv run python scripts/generate_seed_migration.py > db/migrations/0003_seed_catalogs.sql
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTITY_CATALOG = REPO_ROOT / "samples" / "entity-catalog.yaml"
FUND_CATALOG = REPO_ROOT / "data" / "fund-catalog.yaml"


def sql_literal(value: str | None) -> str:
    """Return a Postgres-safe quoted string literal, or NULL for None."""
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_text_array(values: list[str]) -> str:
    """Return Postgres array literal for TEXT[]. Empty list becomes '{}'."""
    if not values:
        return "ARRAY[]::TEXT[]"
    escaped = ["'" + v.replace("'", "''") + "'" for v in values]
    return "ARRAY[" + ", ".join(escaped) + "]::TEXT[]"


def collect_agency_aliases(agency: dict) -> list[str]:
    """Distinct alternative names observed for this agency, excluding the canonical name."""
    canonical = agency["canonical_name"]
    aliases: set[str] = set()

    for name in (agency.get("names_observed_jlbc") or {}).keys():
        # JLBC PDFs sometimes prefix 'Page No.  ' on table-of-contents lines.
        # Strip the prefix so the alias is the actual agency name.
        cleaned = name.removeprefix("Page No.  ").removeprefix("Page No. ").strip()
        if cleaned and cleaned != canonical:
            aliases.add(cleaned)

    gov_alias = agency.get("name_gov_alias")
    if gov_alias and gov_alias != canonical:
        aliases.add(gov_alias)

    return sorted(aliases)


def emit_agencies_sql() -> list[str]:
    catalog = yaml.safe_load(ENTITY_CATALOG.read_text(encoding="utf-8"))
    agencies = catalog["agencies"]

    lines = [
        "-- agencies (Tier 1 entity resolution, " + str(len(agencies)) + " rows)",
        "INSERT INTO agencies (agency_id, canonical_name, short_name, aliases) VALUES",
    ]
    rows = []
    for a in agencies:
        agency_id = a["canonical_id"]
        canonical_name = a["canonical_name"]
        # Slug uppercased is a reasonable short_name candidate (ADC, SBA, AHCCCS).
        # Set NULL when the slug is multi-segment / hyphenated, which usually
        # means there's no canonical acronym (e.g. 'state-treasurer' -> NULL).
        slug = a.get("slug") or ""
        short_name: str | None = slug.upper() if slug and "-" not in slug else None
        aliases = collect_agency_aliases(a)
        rows.append(
            "  ("
            + sql_literal(agency_id)
            + ", "
            + sql_literal(canonical_name)
            + ", "
            + sql_literal(short_name)
            + ", "
            + sql_text_array(aliases)
            + ")"
        )
    lines.append(",\n".join(rows) + "\nON CONFLICT (agency_id) DO UPDATE SET")
    lines.append("  canonical_name = EXCLUDED.canonical_name,")
    lines.append("  short_name     = EXCLUDED.short_name,")
    lines.append("  aliases        = EXCLUDED.aliases;")
    return lines


def emit_funds_sql() -> list[str]:
    catalog = yaml.safe_load(FUND_CATALOG.read_text(encoding="utf-8"))
    funds = catalog["funds"]

    lines = [
        "",
        "-- funds (canonical fund catalog, " + str(len(funds)) + " rows)",
        "INSERT INTO funds (fund_id, canonical_name, short_name, aliases, present_in) VALUES",
    ]
    rows = []
    for f in funds:
        fund_id = f["canonical_id"]
        canonical_name = f["canonical_name"]
        present_in = f.get("present_in") or []
        rows.append(
            "  ("
            + sql_literal(fund_id)
            + ", "
            + sql_literal(canonical_name)
            + ", "
            + "NULL"  # no short_name field on funds yet
            + ", "
            + sql_text_array([])  # aliases populated when fund-catalog.yaml grows the field
            + ", "
            + sql_text_array(present_in)
            + ")"
        )
    lines.append(",\n".join(rows) + "\nON CONFLICT (fund_id) DO UPDATE SET")
    lines.append("  canonical_name = EXCLUDED.canonical_name,")
    lines.append("  short_name     = EXCLUDED.short_name,")
    lines.append("  aliases        = EXCLUDED.aliases,")
    lines.append("  present_in     = EXCLUDED.present_in;")
    return lines


def main() -> None:
    # Force UTF-8 stdout regardless of the host shell's code page (Windows defaults
    # to cp1252, which rejects characters outside Latin-1; explicit reconfigure
    # makes the script behave the same on bash, PowerShell, and cmd.exe).
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")  # type: ignore[union-attr]

    out: list[str] = [
        "-- 0003_seed_catalogs.sql",
        "-- Phase 1b Workstream 1, Task 1.2 Step 3.",
        "-- GENERATED by scripts/generate_seed_migration.py: DO NOT EDIT BY HAND.",
        "-- Regenerate when samples/entity-catalog.yaml or data/fund-catalog.yaml changes.",
        "",
        "BEGIN;",
        "",
    ]
    out.extend(emit_agencies_sql())
    out.extend(emit_funds_sql())
    out.extend(["", "COMMIT;", ""])

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
